components:
  - name: {{ name }}
    type: "frontend"
    replicaCount: 1
    image:
      name: {{ name }}
      tag: "latest"
    service:
      port: 80
    ingress:
      host: {{ name }}
    tls:
      enabled: true

  - name: {{ name }}
    type: "backend"
    replicaCount: 1
    image:
      name: {{ name }}
      tag: "latest"
    service:
      port: 80
      targetPort: {{ port }}
    ingress:
      host: {{ name }}
    tls:
      enabled: true