{{ define "nya.backend" }}
---
# Deployment spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-api" .name }}
  labels:
    app: {{ printf "%s-api" .name }}
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ printf "%s-api" .name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-api" .name }}
      annotations:  # ← ADD THIS
        deployedAt: "{{ .podAnnotations.deployedAt | default "0" }}"
    spec:
      containers:
        - name: {{ printf "%s-api" .name }}
          image: "{{ .registry_host }}/{{ .image.name }}:{{ .image.tag | default "latest" }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .service.targetPort | default 80 }}
              protocol: TCP

---
# Service spec
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-api" .name }}
  labels:
    app: {{ printf "%s-api" .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  ports:
    - port: {{ .service.port | default 80 }}
      targetPort: {{ .service.targetPort | default 80 }}
      protocol: TCP
      name: http
  selector:
    app: {{ printf "%s-api" .name }}

---
# Ingress spec
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-api" .name }}
  labels:
    app: {{ printf "%s-api" .name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ printf "%s-api.%s" .ingress.host .domain | quote }}
      http: 
        paths:
          - path: {{ .ingress.path | default "/" }}
            pathType: {{ .ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ printf "%s-api" .name }}
                port:
                  number: {{ .service.port | default 80 }}
  {{- if .tls.enabled }}
  tls:
    - hosts:
        - {{ printf "%s-api.%s" .ingress.host .domain | quote }}
      secretName: {{ .tls.secretName | default "nya-tls-cert" }}
  {{- end }}
{{- end }}